name: sendingnetwork_dart_sdk
description: sendingnetwork_dart_sdk Dart SDK
version: 0.1.0
homepage: https://github.com/Sending-Network
repository: https://github.com/Sending-Network/sendingnetwork_dart_sdk

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  async: ^2.8.0
  base58check: ^2.0.0
  blurhash_dart: ^1.1.0
  canonical_json: ^1.1.0
  collection: ^1.15.0
  crypto: ^3.0.0
  ffi: ^2.0.0
  hive: ^2.2.3
  html: ^0.15.0
  html_unescape: ^2.0.0
  http: ^1.1.0
  image: ^4.0.15
  js: ^0.6.3
  markdown: ^4.0.0
  sendingnetworkdart_api_lite: ^0.0.9
  mime: ^1.0.0
  olm: ^2.0.2
  random_string: ^2.3.1

  sdp_transform: ^0.3.2
  slugify: ^2.0.0
  typed_data: ^1.3.2
  webrtc_interface: ^1.0.13


dev_dependencies:
  coverage: ">=0.15.0 <2.0.0"
  dart_code_metrics: ^4.10.1
  file: ^6.1.1
  import_sorter: ^4.6.0
  lints: ^2.0.0
  test: ^1.15.7
  #flutter_test: {sdk: flutter}

#dependency_overrides:
#  sendingnetworkdart_api_lite:
#    path: ../sendingnetworkdart_api_lite
